### ISSUE TITLE
哥们，您的图片上传插件不错，感谢分享，遇到个问题

### ISSUE THREAD

**Issue by cynhard** [Monster-L/ajax-upload-image.mobile#1]
在移动端使用，现在手机像素都很高，拍照上传的图片体积一般都很大，您的插件怎么结合js压缩插件使用呢？谢谢

**Comment by Monster-L** [comment]
通过这种方式拿到的是图片base64字符串，你可以通过canvas渲染所需大小图片，再通过 toDataURL 方法压缩保存为base64字符串，最终上传服务器

**Comment by cynhard** [comment]
`canvas.width = expectWidth;
canvas.height = expectHeight;
ctx.drawImage(this, 0, 0, expectWidth, expectHeight);`
  是改这几行代码吗？不知道为啥没效果

**Comment by Monster-L** [comment]
_canvasResize()这个方法是只针对Ios设备才会调用的。但代码逻辑是一样的，你可以通过这种方式缩小拍照拿到的照片，进而减少图片体积

**Comment by cynhard** [comment]
嗯，感谢，我今天试试方法对安卓可行不，另外对上传图片的操作有bug，点击关闭或者删除会把整个网站的body体删掉，自己还没有解决
