### ISSUE TITLE
图片在安卓机上不能显示

### ISSUE THREAD

**Issue by WGinit** [Monster-L/ajax-upload-image.mobile#3]
您好，现在做的移动端网站，我在chromeshan上调试ok，微信开发者工具也可以的，但在安卓机上选择图片后没任何反应，想知道咋回事

**Comment by Monster-L** [comment]
安卓机？是在安卓机默认浏览器中无法使用么？安卓机微信中使用是否正常？

**Comment by lcp0578** [comment]
如果是webview加载的页面，需要安卓特殊处理下，我们利用这个仓库[Android-AdvancedWebView](https://github.com/delight-im/Android-AdvancedWebView)，完美解决了。
